"""
Snapshot-comparison helpers for ABCMB refactor parity tests.

Phase C oracle: compare model output to pytests/fixtures/snapshots.npz
generated by pytests/fixtures/generate_snapshots.py.
"""

import os
import numpy as np

FIXTURES_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                            'fixtures')
SNAPSHOTS_NPZ = os.path.join(FIXTURES_DIR, 'snapshots.npz')


def load_snapshots():
    """Returns the npz handle (mmap'd). Keys are '<scenario>__<field>'."""
    if not os.path.exists(SNAPSHOTS_NPZ):
        raise FileNotFoundError(
            f"Snapshot file not found: {SNAPSHOTS_NPZ}. "
            f"Run pytests/fixtures/generate_snapshots.py to create it."
        )
    return np.load(SNAPSHOTS_NPZ, allow_pickle=True)


def assert_matches_snapshot(scenario, fields, rtol=1e-10, atol=0.0):
    """Compare a dict of {field_name: array} to the snapshot for `scenario`.

    Parameters
    ----------
    scenario : str
        Name of the scenario (e.g., "lcdm_tau"). Must exist in
        snapshots.npz with keys "<scenario>__<field>".
    fields : dict[str, array-like]
        The field values to compare.
    rtol, atol : float
        Tolerances for np.testing.assert_allclose. Default rtol=1e-10
        targets bit-precision modulo XLA fusion noise.
    """
    snap = load_snapshots()
    failures = []
    for fname, value in fields.items():
        key = f"{scenario}__{fname}"
        if key not in snap.files:
            failures.append(f"  missing key {key!r} in snapshot")
            continue
        ref = snap[key]
        cur = np.asarray(value)
        if cur.shape != ref.shape:
            failures.append(
                f"  {fname}: shape mismatch {cur.shape} vs ref {ref.shape}")
            continue
        diff = np.abs(cur - ref)
        ref_abs = np.abs(ref)
        # relative error where ref != 0, absolute elsewhere
        rel = np.where(ref_abs > 0, diff / np.maximum(ref_abs, 1e-300), 0.)
        max_rel = float(rel.max())
        max_abs = float(diff.max())
        # use the same convention as np.testing.assert_allclose
        try:
            np.testing.assert_allclose(cur, ref, rtol=rtol, atol=atol)
        except AssertionError as e:
            failures.append(
                f"  {fname}: max_rel={max_rel:.2e} max_abs={max_abs:.2e}\n"
                f"    rtol={rtol:.0e} atol={atol:.0e}\n"
                f"    {str(e).splitlines()[0]}")
    if failures:
        msg = f"Snapshot mismatch for scenario {scenario!r}:\n" + "\n".join(failures)
        raise AssertionError(msg)
